name: Listener Deploy WebApp

on:
  repository_dispatch:
    types: frontend-autovist-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Clonar o reposit칩rio de c칩digo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # preciso mandar isso para >> $GITHUB_ENV ?
          ref: ${{ github.event.client_payload.branch }}

      - name: 游릭 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 游닍 Instalar depend칡ncias com Yarn
        run: yarn install
